-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvVMoNauq2F43bYPN
jaIetE1ynyUIx2imBxNBbMulyvqgCgYIKoZIzj0DAQehRANCAATTmIOjpGcEK63Z
nVmKfCPl5Z2t4jcoHglyso36SHzcnXED2ZXc+NjmuNsOdnY1CzWBzPLY0Y9m1Gn3
LiD1PWwr
-----END PRIVATE KEY-----