-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrFyAfNpsHZk7L+s1
LJuTuLMkVENKQDWVJfZENeJ4b7+gCgYIKoZIzj0DAQehRANCAASeCKMz30hZB5Ff
EgYrmrtuleatZZ5LLWdcnfW2u+wam8QboQRNDrCKLDfvCQpH5LaA50RWdDRGYkEr
WqH7wf0N
-----END PRIVATE KEY-----